#!/bin/sh

clear

whoiam=$(whoami)

if [ "$whoiam" != "root" ];
then
  echo "please run as root"
  exit 1
fi


read -p "
[1] adafruit
[2] soekris 19200
[3] soekris 57600
[4] rasp pi

? : " cfg


case $cfg in
  1)
    configuration="dfl"
    baudrate="115200"
  ;;
  2)
    configuration="dfl"
    baudrate="19200"
  ;;
  3)
    configuration="dfl"
    baudrate="57600"
  ;;
  4)
    configuration="dfl"
    baudrate="115200"
  ;;
  *)
    echo "exiting ..."
  ;;
esac




echo
echo
echo "Available devices"
ls /dev | grep 'USB0\|USB1\|AMA0\|AMC0'
echo
echo

echo
echo
echo "Available devices"
ls /dev | grep 'USB0\|USB1\|AMA0\|AMC0'
echo
echo


read -p "

Device

[1] USB0
[2] USB1
[3] ACM0
[4] AMA0

? : " dev

case $dev in
  1)
    device="USB0"
  ;;
  2)
    device="USB1"
  ;;
  3)
    device="ACM0"
  ;;
  4)
    device="AMA0"
  ;;
  *)
    echo "exiting ..."
  ;;
esac

echo
echo "minicom -c on device /dev/tty$device -b $baudrate configuration $configuration"
minicom -c on device $device configuration $configuration