#!/bin/sh
vim=$HOME/.vim
dotfiles=$HOME/dotfiles
bin=$HOME/dotfiles



# vim
mkdir $vim
mkdir $vim/swaps
mkdir $vim/backups
mkdir $vim/undo
mkdir $vim/autload
mkdir $vim/bundle




#tmux

# teardown
rm $HOME/.tmux.conf
rm  $HOME/.tmux.macos.conf
rm  $HOME/.tmux.conf.local
rm  $HOME/.tmux.conf.solarized_light

ln -s $dotfiles/tmux.conf $HOME/.tmux.conf
ln -s $dotfiles/tmux.macos.conf $HOME/.tmux.macos.conf
ln -s $dotfiles/tmux.conf.local $HOME/.tmux.conf.local
ln -s $dotfiles/tmux.conf.solarized_light $HOME/.tmux.conf.solarized_light

ln -s $dotfiles/vim/colors $vim/colors
ln -s $dotfiles/vimrc $HOME/.vimrc
ln -s $dotfiles/autoload $vim/autoload
ln -s $dotfiles/bundle $vim/bundle

# bin files
ln -s $bin/serial $HOME/bin/serial
ln -s $bin/utils.sh $HOME/bin/utils.sh
ln -s $bin/on $HOME/bin/on
ln -s $bin/off $HOME/bin/off

# nethack
ln -s $dotfiles/nethackrc $HOME/.nethackrc

# zsh
