#!/bin/sh
VIM=$HOME/.vim
DOTFILES=$HOME/dotfiles



# vim
mkdir $VIM
mkdir $VIM/swaps
mkdir $VIM/backups
mkdir $VIM/undo



#tmux
ln -s $DOTFILES/tmux.conf $HOME/.tmux.conf
ln -s $DOTFILES/tmux.macos.conf $HOME/.tmux.macos.conf

ln -s $DOTFILES/vim/colors $VIM/colors
ln -s $DOTFILES/vimrc $HOME/.vimrc



# nethack
ln -s $DOTFILES/nethackrc $HOME/.nethackrc

# zsh

